# Generated by Django 5.0.6 on 2026-08-17 15:59

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    username = os.environ.get('ADMIN_USERNAME', 'admin')
    email = os.environ.get('ADMIN_EMAIL', 'admin@example.com')
    password = os.environ.get('ADMIN_PASSWORD', 'YourSecurePassword123!')

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username,
            email=email,
            password=password
        )

class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0001_initial'),  # Ensures this runs after your first migration
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
